name: CI

on:
  push:
    branches:
      - main  # Ejecuta en cada push a la rama main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Cambia a la versiÃ³n que necesites

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        make model-test  # Ejecuta las pruebas del modelo

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.IMAGE_NAME }} .  # Construye la imagen

    - name: Push Docker image
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}" > ${{ github.workspace }}/gcp-key.json
        gcloud auth activate-service-account --key-file=${{ github.workspace }}/gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        docker tag ${{ secrets.IMAGE_NAME }} gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.IMAGE_NAME }}
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.IMAGE_NAME }}
